version: '3.9'

services:
    node:
        image: node:lts
        volumes:
            - .:/app
        environment:
            - NODE_ENV
            - NPM_CONFIG_UPDATE_NOTIFIER=false
        user: "${HOST_UID}:${HOST_GID}"
        working_dir: /app
        network_mode: bridge
