name: CI

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Build
                run: make build HOST_UID=0 HOST_GID=0

            -   name: Package
                run: make package

            -   name: Upload Artifact
                uses: actions/upload-artifact@v3
                with:
                    name: sd-web-ui-bit-theme.zip
                    path: dist/sd-web-ui-bit-theme.zip
