name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get metadata
        id: meta
        run: |
          echo "version=$(basename "$GITHUB_REF")" >> $GITHUB_OUTPUT

      - name: Package
        run: make package

      - name: Generate release notes
        id: changelog
        run: make generate-release-notes VERSION=${{ steps.meta.outputs.version }}

      - name: Create release
        id: create_release
        uses: shogo82148/actions-create-release@v1
        with:
          body_path: ${{ github.workspace }}/RELEASE-NOTES.md
          prerelease: ${{ contains(steps.meta.outputs.version, '-') }}

      - name: Upload Package
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/dist/sd-web-ui-bit-theme.zip
          asset_name: sd-web-ui-bit-theme.zip
          asset_content_type: application/zip
